### ISSUE TITLE
Is it possible to read a dynamic value from an input field?

### ISSUE THREAD

**Issue by eklem** [argyleink/blingblingjs#29]
I have an input field:
```html
<input type="text" id="querytext" placeholder="some query words" value="some other words" />
```
I'm trying to read what is the present value of the input field. I tried this, but I only get the predefined value `some other words`:
```
import $ from './blingbling.js'
$('#querytext').on('keydown', e => querytext())

const querytext = function () {
  const [txt] = $(document.querySelector('input#querytext'))
  console.log(txt.attr('value'))
}
```

**Comment by argyleink** [comment]
i believe you want to access the property value not the attribute value.

here's a codepen, see the console as you type/edit https://codepen.io/argyleink/pen/mdBNKNd?editors=1111

**Comment by eklem** [comment]
Great! Thanks for the help 😄
