### ISSUE TITLE
Is it a way to replaceChildren within blingblingjs?

### ISSUE THREAD

**Issue by eklem** [argyleink/blingblingjs#30]
Now I'm doing:
```javaScript
  const node = document.createElement('span').innerText = JSON.stringify(variableName, 2, ' ')
  document.getElementById('idname').replaceChildren(node)
```

But is there a sipmpler way with blingblingjs syntax?

**Comment by eklem** [comment]
Here's the demo:
https://eklem.github.io/words-n-numbers/demo/

HTML: https://github.com/eklem/words-n-numbers/blob/trunk/demo/index.html
JavaScript: https://github.com/eklem/words-n-numbers/blob/trunk/demo/js/demo-app.js

**Comment by eklem** [comment]
Ok, that came off a little bit too much "fix my problem". But what I'm asking if is possible is to do:

```javascript
$('button.rad').attr('rad', true)
```

Only, it's not for an attribute, but for innerHTML or innerText of an element.

**Comment by argyleink** [comment]
> Only, it's not for an attribute, but for innerHTML or innerText of an element.

nah, no helpers in this lib for dom replacing or giving attributes to innerText.

**Comment by eklem** [comment]
Ok, thanks.
