### ISSUE TITLE
pass "JQuery"-name as an parameter/options to give blingblingjs a "new name"

### ISSUE THREAD

**Issue by anoxxxy** [argyleink/blingblingjs#38]
Hi,
some plugins are independent of the jquery name to be able to work, for example Bootstrap 4 or other plugins.

Is it perhaps possible to add the JQuery as an option to blingblingjs and make the other plugins which are dependent of JQuery to work? Of course I do know that those plugins are dependent of JQuery functions which perhaps may not be available in the current state of blingblingjs.

But this functionality would be pretty cool to have!

regards

**Comment by argyleink** [comment]
if you're looking for a minimal jquery, i'd suggest Zepto https://zeptojs.com
