### ISSUE TITLE
a bookmarklet for quick temporary use in the browser console with chrome keyboard shortcuts?

### ISSUE THREAD

**Issue by hchiam** [argyleink/blingblingjs#42]
## why

i can't always install blingblingjs or jQuery for certain projects, but i'd still like to avoid manually typing things like `[...document.querySelectorAll('a')].map(x=>x.addEventListener(` when i'm quickly debugging stuff in the devtools console. it's also a little wasteful to fetch all of jQuery when i usually only need to do a few things with selecting and `.on`.

Using a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet) seems to address this nicely for my own personal use. just thought i'd share [my bookmarklet](https://github.com/hchiam/learning-js/blob/main/bookmarklets/blingbling.js) here.

## how

1) to try it out, create a bookmark (preferably in Chrome) and paste the following into the URL of that new bookmark:

    ```js
    javascript: fetch('https://cdn.jsdelivr.net/npm/blingblingjs@latest/dist/index.min.js')
      .then((x) => x.text())
      .then((x) => {
        eval(x);
        $ = $.default;
        console.log("💲 BlingBlingJS ready 💲");
      });
    ```
    
    https://github.com/hchiam/learning-js/blob/main/bookmarklets/blingbling.js

2) you can now use the following keyboard shortcuts in Chrome to quickly "install" BlingBlingJS on almost any page:

    **mac:** <kbd>command</kbd> + <kbd>L</kbd>, then type to search for the bookmark name, then hit enter --> `$('...').on` now works in the console!
    
    **pc:** <kbd>Ctrl</kbd> + <kbd>L</kbd>, then type to search for the bookmark name, then hit enter --> `$('...').on` now works in the console!
    
    Depending on how uniquely you name your bookmark, you can reach it in a few keystrokes. Note that these keyboard shortcuts may not work for you in Firefox. In Firefox, I give short names for the bookmarklets I use often, and place them within easy reach in the bookmark bar (not inside a folder).
    
    https://github.com/argyleink/blingblingjs/assets/18131787/936f3ab9-b0b5-4d19-b71b-28b8d0cea17e

**Comment by argyleink** [comment]
very cool! 🙏🏻
