### ISSUE TITLE
$.rAF(()=>{})

### ISSUE THREAD

**Issue by argyleink** [argyleink/blingblingjs#5]
sugarrrrrrrrrrrrr

**Comment by hchiam** [comment]
Is RAF short for [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)? Maybe we could take inspiration from https://github.com/FormstoneClassic/Zoetrope/blob/master/jquery.fs.zoetrope.js

**Comment by argyleink** [comment]
it's simpler than that.. as this lib isnt trying to pacify as many browsers as jquery. this is just shorthand because writing `requestAnimationFrame` stinks, just like writing `addEventListener` stinks and this lib offers `on`. 

if this gets done, we should also add `$.rIC()` for `requestIdleCallback`

these feel like perfect candidates for their own import/export too, so they don't come with `$`. usage should be like:

```js
import rIC, rAF from 'blingblingjs'

rAF(_ => {
  // do animation code
})
```
